@extends('layouts.newReport')

@section('title', $title)


@section('content')
    <div class = "rep">
        <br>
        <br>
        <b> {{ $title }} </b>
        </h6>
        <br>
        <b>Generated By:</b><i>: {{ Auth::user()->first_name }} {{ Auth::user()->last_name }} (#{{ Auth::id() }})</i>
        <br>
        <b>Position:</b> <i>{{ Auth::user()->user_role->role }} </i>
        <br>
        <b>Date Generated:</b><i>{{ date('Y-m-d H:i:s') }}</i>
    </div>

    <hr style="width:45%; margin-left: 0.1rem; background-color:gray; height: 2px;" >
    <div class = "timef">
        <h6>
        <b>Timeframe</b>
    </div>
    <div class ="dits">
        <div class="row p-4">
            <div class="column">
                <p class="font-weight-bold">Date Start:</p>
                <p class="font-weight-bold">Date End:</p>
                <p class="font-weight-bold">Sort by:</p>
                <p class="font-weight-bold">Report Type filter:</p>
                <p class="font-weight-bold">Status filter:</p>
            </div>
            <div class="column">
                <p class="text-right"> {{$date_start}} </p>
                <p class="text-right"> {{ $date_end  }} </p>
                <p class="text-right">  {{ str_replace(array("types."),"",$sort_column ); }} ({{{ $sort_option }}}) </p>
                <p class="text-right"> {{ strtoupper($report_option) }} </p>
                <p class="text-right"> {{ strtoupper($status_option) }} </p>
            </div>
            <hr style="width:100%; background-color:gray; height: 2px;" >

            @if ($status_option == 'all')
                <div class="column">
                    <p class="font-weight-bold">Pending Count:</p>
                    <p class="font-weight-bold">Approved Count:</p>
                    <p class="font-weight-bold">Denied Count:</p>
                    <p class="font-weight-bold">Resolved Count:</p>
                </div>
                <div class="column">
                    <p class="text-right"> {{ $reportsData->pending_count }} </p>
                    <p class="text-right"> {{ $reportsData->approved_count }} </p>
                    <p class="text-right"> {{ $reportsData->denied_count }} </p>
                    <p class="text-right"> {{ $reportsData->approved_count }} </p>
                </div>
            @endif
        </div>
    </div>

    <div class="regiz">
        <div class="regi">
            <pre> <b>{{ $modelName }} Submitted:</b> {{ $missingPersons->count() }}</pre>
        </div>
    </div>

    <table class="tableContent mb-4">
        <thead style="background: #F5F5F5;">
            <tr>
                <th>ID</th>
                <th>Submitted By</th>
                <th>Type</th>
                <th>Picture</th>
                <th>Name</th>
                <th>Details</th>
                <th>Unique Information</th>
                <th>Last Seen</th>
                <th>User Contact</th>
                <th>Contact Information</th>
                <th>Status</th>
                <th>Reported Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($missingPersons as $missing_person)
                <tr style="padding: 0px; margin: 0px">
                    <td>{{ $missing_person->id }}</td>
                    <td>{{ $missing_person->user->getFullNameAttribute(). '(#'. $missing_person->user_id .')' }} </td>
                    <td style="width: 30px;">
                        <p><strong>{{ $missing_person->report_type }}</strong></p>
                    </td>

                    <td>
                        <img style="height:150px; max-height: 150px; max-width:150px; width: 150px;" src="{{ asset('storage/'.$missing_person->file_path) }}" class="rounded" alt="{{$missing_person->missing_name}} image">
                    </td>

                    <td>{{ $missing_person->name }}</td>
                    <td style="width: 30px;">
                        <p class="p-0"><span class="font-weight-bold">Age:</span><br>{{ $missing_person->age.' yr old' }}</p>
                        <p class="p-0"><span class="font-weight-bold">Height:</span><br>{{ $missing_person->height.' '. $missing_person->height_unit }}</p>
                        <p class="p-0"><span class="font-weight-bold">Weight:</span><br>{{ $missing_person->weight.' '. $missing_person->weight_unit }}</p>
                        <p class="p-0"><span class="font-weight-bold">Eyes:</span><br>{{ $missing_person->eyes }}</p>
                        <p class="p-0"><span class="font-weight-bold">Hair:</span><br>{{ $missing_person->hair }}</p>
                    </td>

                    <td>{{ $missing_person->unique_sign }}</td>
                    <td>{{ $missing_person->last_seen }}</td>

                        @if ($missing_person->user_id === $missing_person->contact_user_id)
                        <td> Same user </td>
                    @else
                        <td>{{ $missing_person->contact->getFullNameAttribute(). '(#'. $missing_person->contact_user_id .')' . '(Role: '. $missing_person->contact->user_role->role . ' )' }} </td>
                    @endif

                    <td style="width: 30px;">
                        <p class="p-0"><span class="font-weight-bold">Email:</span><br>{{ $missing_person->email}}</p>
                        <p class="p-0"><span class="font-weight-bold">Phone No:</span><br>{{ $missing_person->phone_no}}</p>
                    </td>

                    <td>
                        <p><strong>{{ $missing_person->status }}</strong></p>
                    </td>

                    <td class="tdCreatedAt">{{ date_format($missing_person->created_at,'d-m-Y') }}</td>
                </tr>
            @endforeach

        </tbody>
    </table>

    <div class="regiz">
        <div class="regi">
            <pre> <b>{{ $modelName }} Submitted:</b> {{ $missingPersons->count() }}</pre>
        </div>
    </div>

@endsection
