@extends('layouts.newReport')

@section('title', $title)


@section('content')
    <div class = "rep">
        <br>
        <br>
        <b> {{ $title }} </b>
        </h6>
        <br>
        <b>Generated By:</b><i>: {{ Auth::user()->first_name }} {{ Auth::user()->last_name }} (#{{ Auth::id() }})</i>
        <br>
        <b>Position:</b> <i>{{ Auth::user()->user_role->role }} </i>
        <br>
        <b>Date Generated:</b><i>{{ date('Y-m-d H:i:s') }}</i>
    </div>

    <hr style="width:45%; margin-left: 0.1rem; background-color:gray; height: 2px;" >
    <div class = "timef">
        <h6>
        <b>Timeframe</b>
    </div>
    <div class ="dits">
        <div class="row p-4">
            <div class="column">
                <p class="font-weight-bold">Date Start:</p>
                <p class="font-weight-bold">Date End:</p>
                <p class="font-weight-bold">Sort by:</p>
                <p class="font-weight-bold">Urgency filter:</p>
                <p class="font-weight-bold">Status filter:</p>
            </div>
            <div class="column">
                <p class="text-right"> {{$date_start}} </p>
                <p class="text-right"> {{ $date_end  }} </p>
                <p class="text-right">  {{ str_replace(array("types."),"",$sort_column ); }} ({{{ $sort_option }}}) </p>
                <p class="text-right"> {{ strtoupper($classification_option) }} </p>
                <p class="text-right"> {{ strtoupper($status_option) }} </p>
            </div>
            <hr style="width:100%; background-color:gray; height: 2px;" >

            @if ($status_option == 'all')
                <div class="column">
                    <p class="font-weight-bold">Pending Count:</p>
                    <p class="font-weight-bold">Ignored Count:</p>
                    <p class="font-weight-bold">Invalid Count:</p>
                    <p class="font-weight-bold">Noted Count:</p>
                </div>
                <div class="column">
                    <p class="text-right"> {{ $reportsData->pending_count }} </p>
                    <p class="text-right"> {{ $reportsData->ignored_count }} </p>
                    <p class="text-right"> {{ $reportsData->invalid_count }} </p>
                    <p class="text-right"> {{ $reportsData->noted_count }} </p>
                </div>
            @endif
        </div>
    </div>

    <div class="regiz">
        <div class="regi">
            <pre> <b>{{ $modelName }} Submitted:</b> {{ $reports->count() }}</pre>
        </div>
    </div>

    <table class="tableContent mb-4">
        <thead style="background: #F5F5F5;">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Type</th>
                <th>Classification</th>
                <th>Address</th>
                <th>Description</th>
                <th>Status</th>
                <th>Submitted at</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($reports as $report)
                <tr>
                    <td scope="row">{{ $report->id }}</td>
                    <td>{{ $report->is_anonymous ? 'Anonymous User' :  $report->user->getFullNameAttribute() }}</td>
                    @if ($report->type_id != 0)
                        <td>{{ $report->type->name }}</td>
                    @else
                        <td>Others/Deleted- {{ $report->custom_type }}</td>
                    @endif
                    <td>{{ $report->urgency_classification }}</td>
                    <td>
                        <p class="font-weight-bold">Location Address:</p>
                        <p>{{ $report->location_address }}</p>

                        <p class="font-weight-bold">Landmark:</p>
                        <p>{{ $report->landmark }}</p>
                    </td>
                    <td>{{ $report->description }}</td>
                    <td>
                        <p class="font-weight-bold">Status:</p>
                        <p>{{ $report->status }}</p>

                        @if ($report->admin_message != null)
                            <p class="font-weight-bold">Admin Message:</p>
                            <p>{{ $report->admin_message }}</p>
                        @endif


                    </td>
                    <td>{{ $report->created_at }}</td>
                </tr>
            @endforeach

        </tbody>
    </table>

    <div class="regiz">
        <div class="regi">
            <pre> <b>{{ $modelName }} Submitted:</b> {{ $reports->count() }}</pre>
        </div>
    </div>

@endsection
