@extends('layouts.newReport')

@section('title', $title)

@section('content')
    <div class = "rep">
        <br>
        <br>
        <b> {{ $title }} </b>
        </h6>
        <br>
        <b>Generated By:</b><i>: {{ Auth::user()->first_name }} {{ Auth::user()->last_name }} (#{{ Auth::id() }})</i>
        <br>
        <b>Position:</b> <i>{{ Auth::user()->user_role->role }} </i>
        <br>
        <b>Date Generated:</b><i>{{ date('Y-m-d H:i:s') }}</i>
    </div>

    <hr style="width:45%; margin-left: 0.1rem; background-color:gray; height: 2px;" >
    <div class = "timef">
        <h6>
        <b>Timeframe</b>
    </div>

    <div class ="dits">
        <div class="row p-4">
            <div class="column">
                <p class="font-weight-bold">Date Start:</p>
                <p class="font-weight-bold">Date End:</p>
                <p class="font-weight-bold">Sort by:</p>
            </div>
            <div class="column">
                <p class="text-right"> {{$date_start}} </p>
                <p class="text-right"> {{ $date_end  }} </p>
                <p class="text-right">  {{ str_replace(array("types."),"",$sort_column ); }} ({{{ $sort_option }}}) </p>
            </div>
            <hr style="width:100%; background-color:gray; height: 2px;" >
        </div>
    </div>

    <div class="regiz">
        <div class="regi">
            <pre> <b>{{ $certificate->name }} Generated:</b> {{ $certificateForms->count() }}</pre>
        </div>
    </div>

    <table class="tableContent mb-4">
        <thead style="background: #F5F5F5;">
            <tr>
                <th>ID</th>
                <th>Requested by</th>
                <th>From Order</th>
                <th>Name</th>
                <th>Address</th>
                <th>Submitted at</th>
                <th>Updated at</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($certificateForms as $certificateForm)
                <tr>
                    <td scope="row">{{ $certificateForm->id }}</td>
                    @if ($certificateForm->user_id == null)
                        <td>{{ $certificateForm->orders[0]->name }} (Walkin)</td>
                    @else
                        <td>{{ $certificateForm->user->getFullNameAttribute() }} (#{{ $certificateForm->user_id }})</td>
                    @endif
                    <td>From Order #{{ $certificateForm->orders[0]->id }}</td>
                    <td>{{ $certificateForm->first_name }} {{ ucwords($certificateForm->middle_name[0]).'.' }} {{ $certificateForm->last_name }}</td>
                    <td>{{ $certificateForm->address }}</td>
                    <td>{{ $certificateForm->created_at->format(' jS \\of F Y ') }}</td>
                    <td>{{ $certificateForm->updated_at->format(' jS \\of F Y ') }}</td>
                </tr>
            @endforeach

        </tbody>
    </table>
@endsection
