@extends('layouts.newReport')

@section('title', $title)


@section('content')

<div class = "rep">
        <br>
        <br>
        <b> {{ $title }} </b>
        </h6>
        <br>
        <b>Generated By:</b><i>: {{ Auth::user()->first_name }} {{ Auth::user()->last_name }} (#{{ Auth::id() }})</i>
        <br>
        <b>Position:</b> <i>{{ Auth::user()->user_role->role }} </i>
        <br>
        <b>Date Generated:</b><i>{{ date('Y-m-d H:i:s') }}</i>
    </div>

    <hr style="width:45%; margin-left: 0.1rem; background-color:gray; height: 2px;" >
    <div class = "timef">
        <h6>
        <b>Timeframe</b>
    </div>

    <div class ="dits">
        <div class="row p-4">
            <div class="column" style="font-size: 18px">
                <p class="font-weight-bold">Date Start:</p>
                <p class="font-weight-bold">Date End:</p>
                <p class="font-weight-bold">Sort by:</p>
                <p class="font-weight-bold">Status:</p>
            </div>
            <div class="column" style="font-size: 18px">
                <p class="text-right"> {{$date_start}} </p>
                <p class="text-right"> {{ $date_end  }} </p>
                <p class="text-right">  {{ str_replace(array("orderReports."),"",$sort_column ); }} ({{{ $sort_option }}}) </p>
                <p class="text-right"> {{ $status  }}</p>
            </div>
            <hr style="width:100%; background-color:gray; height: 2px;" >
        </div>
    </div>
    <div class="regiz">
        <div class="regi">
            <pre> <b>{{ $modelName }} count:</b> {{ $orderReports->count() }}</pre>
           
        </div>
    </div>
    <table class="tableContent mb-4">
        <thead style="background: #F5F5F5;">
            <tr>
                <th>ID</th>
                <th>User</th>
                <th>Role</th>
                <th>Order ID</th>
                <th>Report Message</th>
                <th>Admin Respond</th>
                <th>Status</th>
                <th>Date Submitted</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        @forelse ($orderReports as $orderReport)
                            <tr>
                                <td>{{ $orderReport->id }}</td>
                                <td>{{ $orderReport->user->getFullNameAttribute() }} (#{{ $orderReport->user_id }})</td>
                                <td>{{ $orderReport->user->user_role->role }}</td>
                                <td>
                                    
                                        From Transaction #{{ $orderReport->order_id }}
                                
                                </td>

                                <td>{{ $orderReport->body }}</td>

                                <td>
                                    @if ($orderReport->status == 'Noted')
                                        
                                    @elseif ($orderReport->status == 'Pending')
                                       
                                    @endif
                                        {{ $orderReport->status }}
                                    </div>
                                </td>

                                <td>
                                    @if ($orderReport->admin_message == null)
                                        Not yet responded to this report
                                    @else
                                        {{ $orderReport->admin_message }}
                                    @endif

                                    </div>
                                </td>

                                <td>
                                    {{ \Carbon\Carbon::parse($orderReport->created_at)->format('F d, Y') }}
                                </td>
                                <td>
                                    @if ($orderReport->status == 'Noted')
                                        Already responded to this report
                                    @else
                                        <ul class="list-inline m-0">
                                            <li class="list-inline-item mb-1">
                                                    Not Responded
                                                </button>
                                            </li>
                                        </ul>
                                    @endif
                                </td>
                            </tr>
                        @empty
                            <p>No data</p>
                        @endforelse
        </tbody>
    </table>

@endsection