@extends('layouts.newReport')

@section('title', $title)

@section('content')


<div class = "rep">
        <br>
        <br>
        <b> {{ $title }} </b>
        </h6>
        <br>
        <b>Generated By:</b><i>: {{ Auth::user()->first_name }} {{ Auth::user()->last_name }} (#{{ Auth::id() }})</i>
        <br>
        <b>Position:</b> <i>{{ Auth::user()->user_role->role }} </i>
        <br>
        <b>Date Generated:</b><i>{{ date('Y-m-d H:i:s') }}</i>
    </div>

    <hr style="width:45%; margin-left: 0.1rem; background-color:gray; height: 2px;" >
    <div class = "timef">
        <h6>
        <b>Timeframe</b>
    </div>

    <div class ="dits">
        <div class="row p-4">
            <div class="column" style="font-size: 18px">
                <p class="font-weight-bold">Date Start:</p>
                <p class="font-weight-bold">Date End:</p>
                <p class="font-weight-bold">Sort by:</p>
            </div>
            <div class="column" style="font-size: 18px">
                <p class="text-right"> {{$date_start}} </p>
                <p class="text-right"> {{ $date_end  }} </p>
                <p class="text-right">  {{ str_replace(array("auditLogs."),"",$sort_column ); }} ({{{ $sort_option }}}) </p>
            </div>
            <hr style="width:100%; background-color:gray; height: 2px;" >
        </div>
    </div>
    <div class="container mb-3">
    <h4 class="text-center">Overall Statistics</h4>
        <hr/>
        <div class="row">
            <div class="col-sm">
                <div class="row">
                    <div class="col-sm-6">
                    Created:
                    </div>
                    <div class="col-sm-6">
                        <div class="font-weight-bold">{{ $logsData->created_count }}</div>
                    </div>

                    <div class="col-sm-6">
                    Updated:
                    </div>
                    <div class="col-sm-6">
                        <div class="font-weight-bold">{{ $logsData->updated_count }}</div>
                    </div>
                    <div class="col-sm-6">
                    Deleted:
                    </div>
                    <div class="col-sm-6">
                        <div class="font-weight-bold">{{ $logsData->deleted_count }}</div>
                    </div>
                </div>
            </div>
</div>
<div class="regiz">
        <div class="regi">
            <pre> <b>{{ $modelName }} posted:</b> {{ $logs->count() }}</pre>
        </div>
    </div>

    <table class="tableContent mb-4">
        <thead style="background: #F5F5F5;">
            <tr>
                <th>Model</th>
                <th>Events</th>
                <th>Executed by</th>
                <th>Position</th>
                <th>Model ID</th>
                <th>Properties</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
        @foreach ($logs as $log)
                <tr>
                    <td>{{ str_replace('App\\Models\\', "",$log->subject_type);  }}</td>
                    <td>
                        @switch($log->event)
                            @case('created')
                                {{ strtoupper($log->event).' - '.$log->description }}
                                @break
                            @case('updated')
                                {{ strtoupper($log->event).' - '.$log->description }}
                                @break
                            @case('deleted')
                                {{ strtoupper($log->event).' - '.$log->description }}
                                @break
                        @endswitch
                    </td>

                    <td>{{ $log->causer->first_name .' '. $log->causer->last_name }} (#{{$log->causer->id}})</td>
                    <td>
                        {{ $log->causer->user_role->role }}
                    </td>

                    <td>{{ $log->subject_id }}</td>
                    <td>
                        @if (isset($log->properties['attributes']))
                            <div class="m-1">
                                <ul class="list-unstyled">
                                    <li>Attributes:
                                        <ul>
                                            @foreach ($log->properties['attributes'] as $key => $node)
                                                <li>{{ $key }}: {{ $node }}</li>
                                            @endforeach
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        @endif

                        @if (isset($log->properties['old']))
                            <div class="m-1">
                                <ul class="list-unstyled">
                                    <li>Old :
                                        <ul>
                                            @foreach ($log->properties['old'] as $key => $node)
                                                <li>{{ $key }}: {{ $node }}</li>
                                            @endforeach
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        @endif

                    </td>
                    <td>{{ $log->created_at }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection
