
@extends('layouts.newReport')

@section('title', $title)


@section('content')
    <div class = "rep">
        <br>
        <br>
        <b> {{ $title }} </b>
        </h6>
        <br>
        <b>Generated By:</b><i>: {{ Auth::user()->first_name }} {{ Auth::user()->last_name }} (#{{ Auth::id() }})</i>
        <br>
        <b>Position:</b> <i>{{ Auth::user()->user_role->role }} </i>
        <br>
        <b>Date Generated:</b><i>{{ date('Y-m-d H:i:s') }}</i>
    </div>

    <hr style="width:45%; margin-left: 0.1rem; background-color:gray; height: 2px;" >
    <div class = "timef">
        <h6>
        <b>Timeframe</b>
    </div>

    <div class ="dits">
        <div class="row p-4">
            <div class="column" style="font-size: 18px">
                <p class="font-weight-bold">Date Start:</p>
                <p class="font-weight-bold">Date End:</p>
                <p class="font-weight-bold">Sort by:</p>
                <p class="font-weight-bold">Polarity Filter:</p>
                <p class="font-weight-bold">Status:</p>
                <p class="font-weight-bold">Feedback Type:</p>
            </div>
            <div class="column" style="font-size: 18px">
                <p class="text-right"> {{$date_start}} </p>
                <p class="text-right"> {{ $date_end  }} </p>
                <p class="text-right">  {{ str_replace(array("types."),"",$sort_column ); }} ({{{ $sort_option }}}) </p>
                <p class="text-right"> {{ $polarity_option  }} </p>
                <p class="text-right"> {{ $status_option  }} </p>
                <p class="text-right"> {{ $modelName  }} </p>
            </div>
            <hr style="width:100%; background-color:gray; height: 2px;" >
        </div>
    </div>

    <div class="container mb-3">

        <h4 class="text-center">Overall Statistics</h4>
        <hr/>
        <div class="row">
            <div class="col-sm">
                <div class="row">
                    <div class="col-sm-6">
                        Positive:
                    </div>
                    <div class="col-sm-6">
                        <div class="font-weight-bold">{{ $feedbacksData->positive_count }} ({{ $feedbacksData->feedbacks_count ? number_format(round($feedbacksData->positive_count * 100 / $feedbacksData->feedbacks_count),0,'.','') . '%' : '0%' }})</div>
                    </div>

                    <div class="col-sm-6">
                        Neutral:
                    </div>
                    <div class="col-sm-6">
                        <div class="font-weight-bold">{{ $feedbacksData->neutral_count }} ({{ $feedbacksData->feedbacks_count ? number_format(round($feedbacksData->neutral_count * 100 / $feedbacksData->feedbacks_count),0,'.','') . '%' : '0%' }})</div>
                    </div>
                    <div class="col-sm-6">
                        Negative:
                    </div>
                    <div class="col-sm-6">
                        <div class="font-weight-bold">{{ $feedbacksData->negative_count }} ({{ $feedbacksData->feedbacks_count ? number_format(round($feedbacksData->negative_count * 100 / $feedbacksData->feedbacks_count),0,'.','') . '%' : '0%' }})</div>
                    </div>
                </div>
            </div>

            <div class="col-sm">
                <div class="row">
                    <div class="col-sm-6">
                        Pending Count:
                    </div>
                    <div class="col-sm-6">
                        <div class="font-weight-bold">{{ $feedbacksData->pending_count }}</div>
                    </div>

                    <div class="col-sm-6">
                        Noted Count:
                    </div>
                    <div class="col-sm-6">
                        <div class="font-weight-bold">{{ $feedbacksData->noted_count }}</div>
                    </div>

                    <div class="col-sm-6">
                        Ignoted Count:
                    </div>
                    <div class="col-sm-6">
                        <div class="font-weight-bold">{{ $feedbacksData->ignored_count }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="regiz">
        <div class="regi">
            <pre> <b>Feedbacks count:</b> {{ $feedbacks->count() }}</pre>
        </div>
    </div>

        <table class="tableContent mb-4">
        <thead style="background: #F5F5F5;">
            <tr>
                <th>ID</th>
                <th>Submitted by</th>
                <th>Feedback Type</th>
                <th>Polarity</th>
                <th>Message</th>
                <th>Admin Respond</th>
                <th>Status</th>
                <th>Date Submitted</th>
                <th>Date Updated</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($feedbacks as $feedback)
                <tr>
                    <td>{{ $feedback->id }}</td>
                    <td>{{ $feedback->is_anonymous ? 'Anonymous User' :  $feedback->user->getFullNameAttribute() }}</td>
                    @if ($feedback->type_id != 0)
                        <td>{{ $feedback->type->name }}</td>
                    @else
                        <td>Others/Deleted- {{ $feedback->custom_type }}</td>
                    @endif
                    <td>{{ $feedback->polarity}}</td>
                    <td>{{ $feedback->message}}</td>
                    @if (!empty($feedback->admin_respond))
                        <td>{{ $feedback->admin_respond }}</td>
                    @else
                        <td>Not yet responded</td>
                    @endif

                    <td>{{ $feedback->status}}</td>
                    <td>{{ $feedback->created_at }}</td>
                    <td>{{ $feedback->updated_at }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection
