
@extends('layouts.newReport')

@section('title', $title)


@section('content')
    <div class = "rep">
        <br>
        <br>
        <b> {{ $title }} </b>
        </h6>
        <br>
        <b>Generated By:</b><i>: {{ Auth::user()->first_name }} {{ Auth::user()->last_name }} (#{{ Auth::id() }})</i>
        <br>
        <b>Position:</b> <i>{{ Auth::user()->user_role->role }} </i>
        <br>
        <b>Date Generated:</b><i>{{ date('Y-m-d H:i:s') }}</i>
    </div>

    <hr style="width:45%; margin-left: 0.1rem; background-color:gray; height: 2px;" >
    <div class = "timef">
        <h6>
        <b>Timeframe</b>
    </div>

    <div class ="dits">
        <div class="row p-4">
            <div class="column" style="font-size: 18px">
                <p class="font-weight-bold">Date Start:</p>
                <p class="font-weight-bold">Date End:</p>
                <p class="font-weight-bold">Sort by:</p>
                <p class="font-weight-bold">Status:</p>
                <p class="font-weight-bold">Feedback Type:</p>
            </div>
            <div class="column" style="font-size: 18px">
                <p class="text-right"> {{$date_start}} </p>
                <p class="text-right"> {{ $date_end  }} </p>
                <p class="text-right">  {{ str_replace(array("types."),"",$sort_column ); }} ({{{ $sort_option }}}) </p>
                <p class="text-right"> {{ $status_option  }} </p>
                <p class="text-right"> {{ $modelName  }} </p>
            </div>
            <hr style="width:100%; background-color:gray; height: 2px;" >
        </div>
    </div>

    <div class="container mb-3">

        <h4 class="text-center">Overall Statistics</h4>
        <hr/>
        <div class="row">
            <div class="col-sm">
                <div class="row">
                    <div class="col-sm-6">
                        Pending Count:
                    </div>
                    <div class="col-sm-6">
                        <div class="font-weight-bold">{{ $inquiriesData->pending_count }}</div>
                    </div>

                    <div class="col-sm-6">
                        Noted Count:
                    </div>
                    <div class="col-sm-6">
                        <div class="font-weight-bold">{{ $inquiriesData->noted_count }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="regiz">
        <div class="regi">
            <pre> <b>Inquiries count:</b> {{ $inquiries->count() }}</pre>
        </div>
    </div>
        <table class="tableContent mb-4">
        <thead style="background: #F5F5F5;">
            <tr>
                <th>ID</th>
                <th>Submitted by</th>
                <th>About</th>
                <th>Message</th>
                <th>Admin Respond</th>
                <th>Status</th>
                <th>Date Submitted</th>
                <th>Date Updated</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($inquiries as $inquiry)
                <tr>
                    <td>{{ $inquiry->id }}</td>
                    <td>{{ $inquiry->user->getFullNameAttribute() }}</td>
                    <td>{{ $inquiry->about}}</td>
                    <td>{{ $inquiry->message}}</td>
                    @if (!empty($inquiry->admin_message))
                        <td>{{ $inquiry->admin_message }}</td>
                    @else
                        <td>Not yet responded</td>
                    @endif
                    <td>{{ $inquiry->status}}</td>
                    <td>{{ $inquiry->created_at }}</td>
                    <td>{{ $inquiry->updated_at }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection
