@extends('layouts.newReport')

@section('title', $title)

@section('content')

<div class = "rep">
        <br>
        <br>
        <b> {{ $title }} </b>
        </h6>
        <br>
        <b>Generated By:</b><i>: {{ Auth::user()->first_name }} {{ Auth::user()->last_name }} (#{{ Auth::id() }})</i>
        <br>
        <b>Position:</b> <i>{{ Auth::user()->user_role->role }} </i>
        <br>
        <b>Date Generated:</b><i>{{ date('Y-m-d H:i:s') }}</i>
    </div>

    <hr style="width:45%; margin-left: 0.1rem; background-color:gray; height: 2px;" >
    <div class = "timef">
        <h6>
        <b>Timeframe</b>
    </div>

    <div class ="dits">
        <div class="row p-4">
            <div class="column" style="font-size: 18px">
                <p class="font-weight-bold">Date Start:</p>
                <p class="font-weight-bold">Date End:</p>
                <p class="font-weight-bold">Sort by:</p>
                <p class="font-weight-bold">Filter:</p>
            </div>
            <div class="column" style="font-size: 18px">
                <p class="text-right"> {{$date_start}} </p>
                <p class="text-right"> {{ $date_end  }} </p>
                <p class="text-right">  {{ str_replace(array("users."),"",$sort_column ); }} ({{{ $sort_option }}}) </p>
                <p class="text-right"> {{ strtoupper($filter)  }} </p>

            </div>
            <hr style="width:100%; background-color:gray; height: 2px;" >
        </div>

    </div>

    <div class ="dits">

        <div class="row p-4">
            <div class="column" style="font-size: 18px">
                <p class="font-weight-bold">Verified User:</p>
                <p class="font-weight-bold">Unverified User:</p>
                <p class="font-weight-bold">Enabled User:</p>
                <p class="font-weight-bold">Restricted User:</p>
            </div>
            <div class="column" style="font-size: 18px">
                @if ($filter == "all")
                    <p class="text-right"> {{ $usersData->verified_user_count }} </p>
                    <p class="text-right"> {{ $usersData->unverified_user_count }} </p>
                    <p class="text-right"> {{ $usersData->enable_user_count }} </p>
                    <p class="text-right">{{ $usersData->disable_user_count }}</p>
                @endif

            </div>

        </div>

    </div>

    <div class="regiz">
        <div class="regi">
            <pre> <b>{{ $modelName }} count:</b> {{ $users->count() }}</pre>
        </div>
    </div>


    <table class="tableContent mb-4">
        <thead style="background: #F5F5F5;">
            <tr>
                <th>ID</th>
                <th>First Name</th>
                <th>Middle Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Account Type</th>
                <th>Verification Status</th>
                <th>Account Status</th>
                <th>Registered At</th>
                <th>Updated At</th>
            </tr>
        </thead>
        <tbody>
             @foreach ($users as $user)
                <tr>
                <td>{{$user->id}}</td>
                    <td>{{$user->first_name}}</td>
                    <td>{{$user->middle_name }}</td>
                    <td>{{$user->last_name }}</td>
                    <td>{{$user->email}}</td>
                    <td>{{$user->user_role->role}}</td>
                    <td>{{$user->status == 'Enable' ? 'Enable Access' : 'Restricted Access'}}</td>
                    <td>{{$user->is_verified == 1 ? 'Verified' : 'Unverified' }}</td>
                    <td>{{ $user->created_at }}</td>
                    <td>{{ $user->updated_at }}</td>
                </tr>
            @endforeach

        </tbody>
    </table>

@endsection
