@extends('layouts.report')

{{-- Title Page --}}
@section('title', 'Feedbacks Report')

@section('content')
    <div class="row">
        <div class="col-xs-6">
            <h4>Feedbacks Report</h4>
            <address>
                <span><strong>Generated By: </strong>{{ Auth::user()->first_name }} {{ Auth::user()->last_name }} (#{{ Auth::id() }})</span><br>
                <span><strong>Position: </strong>{{ Auth::user()->user_role->role }} </span><br>
                <span><strong>Date Generated: </strong>{{ date('Y-m-d H:i:s') }}</span><br>
                <hr>
                @if ($request->polarity_option == 'all')
                    <h5 class="text-center"><strong>Overall Statistics</strong></h5>
                    <span><strong>Positive: </strong>{{ $feedbacksData->positive_count }} ({{ $feedbacksData->feedbacks_count ? number_format(round($feedbacksData->positive_count * 100 / $feedbacksData->feedbacks_count),0,'.','') . '%' : '0%' }})</span><br>
                    <span><strong>Neutral: </strong>{{ $feedbacksData->neutral_count }} ({{ $feedbacksData->feedbacks_count ? number_format(round($feedbacksData->neutral_count * 100 / $feedbacksData->feedbacks_count),0,'.','') . '%' : '0%' }})</span><br>
                    <span><strong>Negative: </strong>{{ $feedbacksData->negative_count }} ({{ $feedbacksData->feedbacks_count ? number_format(round($feedbacksData->negative_count * 100 / $feedbacksData->feedbacks_count),0,'.','') . '%' : '0%' }})</span><br>
                @endif
            </address>

        </div>

        <div class="col-xs-5">
            <h4 class="text-center"><strong>Timeframe</strong></h4>
            <table style="width: 100%">
                <tbody>
                    <tr>
                        <th>Date Start: </th>
                        <td class="text-right">{{ $request->date_start }}</td>
                    </tr>

                    <tr>
                        <th>Date End: </th>
                        <td class="text-right">{{ $request->date_end }}</td>
                    </tr>
                    <tr>
                        <th>Sort By: </th>
                        <td class="text-right">{{ str_replace(array("ordinances."),"",$request->sort_column ); }} ({{{ $request->sort_option }}})</td>
                    </tr>
                    <tr>
                        <th>Polarity filter: </th>
                        <td class="text-right">{{ strtoupper($request->polarity_option) }}</td>
                    </tr>

                    <tr>
                        <th>Status filter: </th>
                        <td class="text-right">{{ strtoupper($request->status_option) }}</td>
                    </tr>

                </tbody>
            </table>

            <hr>
            @if ($request->status_option == 'all')
                <table style="width: 100%">
                    <tbody>
                        <tr>
                            <th>Pending Count: </th>
                            <td class="text-right">{{ $feedbacksData->pending_count }}</td>
                        </tr>

                        <tr>
                            <th>Noted Count: </th>
                            <td class="text-right">{{ $feedbacksData->noted_count }}</td>
                        </tr>

                        <tr>
                            <th>Ignored Count: </th>
                            <td class="text-right">{{ $feedbacksData->ignored_count }}</td>
                        </tr>
                    </tbody>
                </table>
            @endif

            <div style="margin-bottom: 0px">&nbsp;</div>

            <table style="width: 100%; margin-bottom: 20px">
                <tbody>

                    <tr class="well" style="padding: 5px">
                        <th style="padding: 5px"><div> Feedback Received: </div></th>
                        <td style="padding: 5px" class="text-right"><strong> {{ $feedbacks->count() }} </strong></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <table>
        <thead style="background: #F5F5F5;">
            <tr>
                <th>ID</th>
                <th>Submitted by</th>
                <th>Feedback Type</th>
                <th>Polarity</th>
                <th>Message</th>
                <th>Admin Respond</th>
                <th>Status</th>
                <th>Date Submitted</th>
                <th>Date Updated</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($feedbacks as $feedback)
                <tr>
                    <td>{{ $feedback->id }}</td>
                    <td>{{ $feedback->is_anonymous ? 'Anonymous User' :  $feedback->user->getFullNameAttribute() }}</td>
                    {{-- @if ($feedback->type_id != 0)
                        <td>{{ $feedback->type->name }}</td>
                    @else
                        <td>Others/Deleted- {{ $feedback->custom_type }}</td>
                    @endif
                    <td>{{ $feedback->polarity}}</td>
                    <td>{{ $feedback->message}}</td>
                    @if (!empty($feedback->admin_respond))
                        <td>{{ $feedback->admin_respond }}</td>
                    @else
                        <td>Not yet responded</td>
                    @endif --}}

                    <td>{{ $feedback->status}}</td>
                    <td>{{ $feedback->created_at }}</td>
                    <td>{{ $feedback->updated_at }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="row">
        <div class="col-xs-6"></div>
        <div class="col-xs-5">
            <table style="width: 100%">
                <tbody>
                    <tr class="well" style="padding: 5px">
                        <th style="padding: 5px"><div> Feedback Received: </div></th>
                        <td style="padding: 5px" class="text-right"><strong> {{ $feedbacks->count() }} </strong></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

@endsection


