@extends('layouts.report')

{{-- Title Page --}}
@section('title', 'User Registration Report')

@section('content')
    <div class="row">
        <div class="col-xs-6">
            <h4>User Registration Report</h4>
            <address>
                <span><strong>Generated By: </strong>{{ Auth::user()->first_name }} {{ Auth::user()->last_name }} (#{{ Auth::id() }})</span><br>
                <span><strong>Position: </strong>{{ Auth::user()->user_role->role }} </span><br>
                <span><strong>Date Generated: </strong>{{ date('Y-m-d H:i:s') }}</span><br>
                <hr>
                @if ($request->polarity_option == 'all')
                    <h5 class="text-center"><strong>Overall Statistics</strong></h5>
                    <span><strong>Positive: </strong>{{ $usersData->positive_count }} ({{ $usersData->users_count ? number_format(round($usersData->positive_count * 100 / $usersData->users_count),0,'.','') . '%' : '0%' }})</span><br>
                    <span><strong>Neutral: </strong>{{ $usersData->neutral_count }} ({{ $usersData->users_count ? number_format(round($usersData->neutral_count * 100 / $usersData->users_count),0,'.','') . '%' : '0%' }})</span><br>
                    <span><strong>Negative: </strong>{{ $usersData->negative_count }} ({{ $usersData->users_count ? number_format(round($usersData->negative_count * 100 / $usersData->users_count),0,'.','') . '%' : '0%' }})</span><br>
                @endif
            </address>

        </div>

        <div class="col-xs-5">
            <h4 class="text-center"><strong>Timeframe</strong></h4>
            <table style="width: 100%">
                <tbody>
                    <tr>
                        <th>Date Start: </th>
                        <td class="text-right">{{ $request->date_start }}</td>
                    </tr>

                    <tr>
                        <th>Date End: </th>
                        <td class="text-right">{{ $request->date_end }}</td>
                    </tr>
                    <tr>
                        <th>Sort By: </th>
                        <td class="text-right">{{ str_replace(array("ordinances."),"",$request->sort_column ); }} ({{{ $request->sort_option }}})</td>
                    </tr>
                    <tr>
                        <th>Filter: </th>
                        <td class="text-right">{{ strtoupper($request->filter) }}</td>
                    </tr>
                </tbody>
            </table>

            <hr>
            @if ($request->filter == 'all')
                <table style="width: 100%">
                    <tbody>
                        <tr>
                            <th>Verified User: </th>
                            <td class="text-right">{{ $usersData->verified_user_count }}</td>
                        </tr>

                        <tr>
                            <th>Unverified User: </th>
                            <td class="text-right">{{ $usersData->unverified_user_count }}</td>
                        </tr>

                        <tr>
                            <th>Enabled User: </th>
                            <td class="text-right">{{ $usersData->enable_user_count }}</td>
                        </tr>

                        <tr>
                            <th>Restricted User: </th>
                            <td class="text-right">{{ $usersData->disable_user_count }}</td>
                        </tr>
                    </tbody>
                </table>
            @endif

            <div style="margin-bottom: 0px">&nbsp;</div>

            <table style="width: 100%; margin-bottom: 20px">
                <tbody>

                    <tr class="well" style="padding: 5px">
                        <th style="padding: 5px"><div> Registered User Count: </div></th>
                        <td style="padding: 5px" class="text-right"><strong> {{ $users->count() }} </strong></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <table class="table">
        <thead style="background: #F5F5F5;">
            <tr>
                <th>ID</th>
                <th>First Name</th>
                <th>Middle Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Account Type</th>
                <th>Verification Status</th>
                <th>Account Status</th>
                <th>Registered At</th>
                <th>Updated At</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($users as $user)
                <tr>
                    <td>{{$user->id}}</td>
                    <td>{{$user->first_name}}</td>
                    <td>{{$user->middle_name }}</td>
                    <td>{{$user->last_name }}</td>
                    <td>{{$user->email}}</td>
                    <td>{{$user->user_role->role}}</td>
                    <td>{{$user->status == 'Enable' ? 'Enable Access' : 'Restricted Access'}}</td>
                    <td>{{$user->is_verified == 1 ? 'Verified' : 'Unverified' }}</td>
                    <td>{{ $user->created_at }}</td>
                    <td>{{ $user->updated_at }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="row">
        <div class="col-xs-6"></div>
        <div class="col-xs-5">
            <table style="width: 100%">
                <tbody>
                    <tr class="well" style="padding: 5px">
                        <th style="padding: 5px"><div> Registered User Count: </div></th>
                        <td style="padding: 5px" class="text-right"><strong> {{ $users->count() }} </strong></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

@endsection


